# Generated by Django 4.2.2 on 2023-07-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('Itemid', models.IntegerField(primary_key=True, serialize=False)),
                ('Itemname', models.CharField(max_length=100)),
                ('Pid', models.IntegerField()),
            ],
            options={
                'db_table': 'itemsTable',
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'districtTable',
            },
        ),
    ]
